### PR TITLE
25-big-file-export

### PR DESCRIPTION
**Pull request by AOneP**

### CODE REVIEW

**Comment by morgoth** [comment]
is this one obsolete? https://github.com/tiramizoo/dataclips/pull/12

**Comment by AOneP** [comment]
@morgoth this PR changes the icon.
Mentioned #12 changes the timezone in downloaded file.

**Comment by AOneP** [comment]
@morgoth this one.

**Comment by morgoth** [comment]
@AOneP it's deployed to analytics. Please verify if all is ok there

**Pull request merged**
